from simplenb import naivebayes

nb = naivebayes.NaiveBayes()
nb.stop_word = ["the", "to"]
nb.train("validate", "validate command")
nb.train("get", "get capability name")
nb.train("get", "get device capability commands")
nb.train("execute", "execute command")
nb.train("handle", "handle things")
nb.train("set", "set fans")
nb.train("set", "main page")
nb.train("execute", "beacon handler")
nb.train("if", "changed location mode")
nb.train("take", "take action")
nb.train("get", "get device type")
nb.train("get", "get usn qualifier")
nb.train("get", "get device name")
nb.train("get", "get name space")
nb.train("add", "add device")
nb.train("resolve", "resolve dni address")
nb.train("get", "get parsers")
nb.train("if", "on location")
nb.train("get", "get verified devices")
nb.train("get", "get devices")
nb.train("subscribe", "subscribe events")
nb.train("execute", "event handler")
nb.train("execute", "mode change handler")
nb.train("if", "scheduled time handler")
nb.train("execute", "app touch handler")
nb.train("execute", "sunrise sunset time handler")
nb.train("execute", "motion handler")
nb.train("execute", "lights handler")
nb.train("execute", "dimmers handler")
nb.train("execute", "illuminance handler")
nb.train("turn", "turn on lights")
nb.train("turn", "turn on dimmers")
nb.train("turn", "turn off lights")
nb.train("turn", "turn off dimmers")
nb.train("execute", "contact open handler")
nb.train("execute", "motion active handler")
nb.train("configure", "configure button")
nb.train("get", "get button sections")
nb.train("execute", "execute handlers")
nb.train("find", "find msg")
nb.train("turn", "turn on camera")
nb.train("turn", "turn off camera")
nb.train("turn", "turn off")
nb.train("turn", "turn on")
nb.train("send", "send text")
nb.train("execute", "water handler")
nb.train("if", "on off handler")
nb.train("execute", "color handler")
nb.train("get", "get random color master")
nb.train("execute", "temp handler")
nb.train("if", "scheduled turn off")
nb.train("execute", "motion inactive handler")
nb.train("set", "default page")
nb.train("initialize", "initialize devices")
nb.train("execute", "coop door state handler")
nb.train("handle", "handle event")
nb.train("execute", "switch handler")
nb.train("set", "auth page")
nb.train("get", "get ecobee thermostats")
nb.train("get", "get thermostat display name")
nb.train("get", "get thermostat type name")
nb.train("execute", "poll handler")
nb.train("update", "update sensor data")
nb.train("get", "get child device ids string")
nb.train("get", "get child name")
nb.train("get", "get sensor child name")
nb.train("get", "get server url")
nb.train("get", "get shard url")
nb.train("get", "get callback url")
nb.train("get", "get build redirect url")
nb.train("get", "get api endpoint")
nb.train("get", "get smart things client id")
nb.train("debug", "debug event")
nb.train("send", "send push and feeds")
nb.train("send", "send activity feeds")
nb.train("convert", "convert fc ")
nb.train("send", "send message")
nb.train("execute", "meter handler")
nb.train("execute", "door handler")
nb.train("set", "first page")
nb.train("set", "input page")
nb.train("set", "input boolean page")
nb.train("set", "input icon page")
nb.train("set", "input image page")
nb.train("add", "add values")
nb.train("add", "add group")
nb.train("set", "input selection page")
nb.train("set", "input text page")
nb.train("set", "input time page")
nb.train("set", "input device page")
nb.train("set", "input capability page")
nb.train("set", "input room page")
nb.train("set", "input mode page")
nb.train("set", "input hub page")
nb.train("set", "input contact book page")
nb.train("set", "app page")
nb.train("set", "label page")
nb.train("set", "mode page")
nb.train("set", "paragraph page")
nb.train("set", "href page")
nb.train("set", "buttons page")
nb.train("set", "image page")
nb.train("set", "video page")
nb.train("if", "flattened page")
nb.train("execute", "water wet handler")
nb.train("get", "get cameras")
nb.train("add", "add cameras")
nb.train("get", "get device info")
nb.train("execute", "location handler")
nb.train("execute", "acceleration handler")
nb.train("send", "send text message")
nb.train("update", "update sms history")
nb.train("if", "on command")
nb.train("set", "root page")
nb.train("set", "unsupported devices page")
nb.train("set", "controller explanation page")
nb.train("set", "numbers page")
nb.train("start", "start level label")
nb.train("set", "scheduling page")
nb.train("set", "completion page")
nb.train("execute", "app handler")
nb.train("stop", "stop dimmers handler")
nb.train("if", "scheduled start")
nb.train("send", "send start event")
nb.train("send", "send stop event")
nb.train("send", "send time remaining event")
nb.train("send", "send controller event")
nb.train("get", "get controller")
nb.train("update", "update dimmers")
nb.train("resume", "resume playing")
nb.train("set", "set levels in state")
nb.train("get", "get hue")
nb.train("get", "get up hue")
nb.train("get", "get down hue")
nb.train("set", "numbers page href description")
nb.train("if", "has start level")
nb.train("if", "has end level")
nb.train("get", "get all devices")
nb.train("set", "set cool temp")
nb.train("set", "set heat temp")
nb.train("set", "set fan mode")
nb.train("set", "set thermostat mode")
nb.train("get", "get thermostat status")
nb.train("turn", "turn on light")
nb.train("turn", "turn off light")
nb.train("get", "get light status")
nb.train("set", "set color")
nb.train("get", "get color status")
nb.train("set", "set kelvin")
nb.train("get", "get kelvin status")
nb.train("get", "get level status")
nb.train("set", "set level status")
nb.train("get", "get contact status")
nb.train("get", "get smoke status")
nb.train("get", "get garage status")
nb.train("get", "get shade status")
nb.train("get", "get water sensor status")
nb.train("get", "get battery status")
nb.train("get", "get door lock status")
nb.train("get", "get presence status")
nb.train("get", "get motion status")
nb.train("get", "get outlet status")
nb.train("get", "get meter status")
nb.train("turn", "turn on outlet")
nb.train("turn", "turn off outlet")
nb.train("get", "get switch status")
nb.train("turn", "turn on switch")
nb.train("turn", "turn off switch")
nb.train("get", "get temp sensors status")
nb.train("execute", "outlet handler")
nb.train("update", "update door lock")
nb.train("update", "update outlet")
nb.train("update", "update switch")
nb.train("execute", "execute action")
nb.train("create", "create subscriptions")
nb.train("switch", "switch off handler")
nb.train("execute", "switch on handler")
nb.train("set", "page with ip")
nb.train("execute", "registration handler")
nb.train("get", "get hue bridges")
nb.train("get", "get verified hue bridges")
nb.train("add", "add bulbs")
nb.train("add", "add bridge")
nb.train("execute", "ssdp bridge handler")
nb.train("do", "do device sync")
nb.train("if", "is valid source")
nb.train("if", "is in bulb discovery")
nb.train("update", "update handler")
nb.train("set", "set level")
nb.train("set", "set saturation")
nb.train("set", "set hue")
nb.train("set", "set color temperature")
nb.train("convert", "convert bulb list map")
nb.train("execute", "humidity handler")
nb.train("add", "add subscription")
nb.train("remove", "remove subscription")
nb.train("execute", "device handler")
nb.train("get", "get access key")
nb.train("get", "get bucket key")
nb.train("set", "set bucket key")
nb.train("set", "set access key")
nb.train("try", "try create bucket")
nb.train("execute", "generic handler")
nb.train("try", "try ship events")
nb.train("execute", "acceleration active handler")
nb.train("execute", "temperature handler")
nb.train("build", "build redirect url")
nb.train("receive", "receive token")
nb.train("if", "received token")
nb.train("validate", "validate current token")
nb.train("set", "set color ")
nb.train("execute", "hook event handler")
nb.train("execute", "cooling setpoint handler")
nb.train("execute", "heating setpoint handler ")
nb.train("execute", "heating setpoint handler")
nb.train("execute", "acceleration inactive handler")
nb.train("check", "check running")
nb.train("execute", "contact handler")
nb.train("get", "get credentials page")
nb.train("get", "get credentials error page")
nb.train("initialize", "initialize life connection")
nb.train("create", "create circle subscription")
nb.train("generate", "generate initial event ")
nb.train("execute", "place event handler")
nb.train("get", "get secret key")
nb.train("get", "get client id")
nb.train("update", "update devices")
nb.train("set", "page setup")
nb.train("set", "page setup scenario a")
nb.train("set", "page setup scenario b")
nb.train("set", "page setup scenario c")
nb.train("set", "page setup scenario d")
nb.train("if", "on event a")
nb.train("if", "on press a")
nb.train("if", "on event b")
nb.train("if", "on press b")
nb.train("if", "on event c")
nb.train("if", "on press c")
nb.train("if", "on event d")
nb.train("if", "on press d")
nb.train("if", "greyed out time")
nb.train("get", "get title")
nb.train("get", "get desc")
nb.train("get", "get midnight")
nb.train("get", "get time label")
nb.train("execute", "contact closed handler")
nb.train("execute", "presence handler")
nb.train("if", "is active presence")
nb.train("set", "set time callback")
nb.train("get", "get servercallback url")
nb.train("get", "get harmonydevices")
nb.train("get", "get activity list")
nb.train("get", "get activity name")
nb.train("get", "get activity id")
nb.train("get", "get hub name")
nb.train("send", "send notification")
nb.train("get", "get device")
nb.train("update", "update device")
nb.train("execute", "execute phrase")
nb.train("send", "send harmony")
nb.train("get", "get hub")
nb.train("get", "get harmony")
nb.train("delete", "delete harmony")
nb.train("check", "check open draw in past")
nb.train("check", "check open draw after reminder")
nb.train("if", "is opened")
nb.train("set", "set led notification")
nb.train("reset", "reset led notification")
nb.train("if", "is moved")
nb.train("get", "get time window msec")
nb.train("execute", "button handler")
nb.train("set", "scenes page")
nb.train("set", "scene page")
nb.train("set", "device page")
nb.train("if", "save states page")
nb.train("execute", "position handler")
nb.train("refresh", "refresh token")
nb.train("get", "get device list")
nb.train("create", "create child device")
nb.train("set", "page two")
nb.train("execute", "touch handler")
nb.train("set", "set sunrise")
nb.train("set", "set sunset")
nb.train("set", "set away")
nb.train("set", "set timer")
nb.train("reset", "reset hue")
nb.train("start", "start timer callback")
nb.train("stop", "stop timer callback")
nb.train("get", "get inputs")
nb.train("register", "register all device subscriptions")
nb.train("execute", "device event handler")
nb.train("execute", "location event handler")
nb.train("execute", "moisture handler")
nb.train("execute", "battery handler")
nb.train("get", "get device serial from event")
nb.train("parse", "parse api response")
nb.train("update", "update wink subscriptions")
nb.train("create", "create wink subscription")
nb.train("delete", "delete wink subscription")
nb.train("remove", "remove wink subscriptions")
nb.train("build", "build callback url")
nb.train("create", "create nimbus children")
nb.train("execute", "cloud clock event handler")
nb.train("get", "get eggtray update")
nb.train("run", "run egg report")
nb.train("execute", "eggtray event handler")
nb.train("get", "get piggy bank update")
nb.train("execute", "piggy bank event handler")
nb.train("get", "get sensor pod update")
nb.train("execute", "sensor pod event handler")
nb.train("execute", "powerstrip event handler")
nb.train("create", "create powerstrip children")
nb.train("set", "set home")
nb.train("send", "send away")
nb.train("send", "send home")
nb.train("send", "send http")
nb.train("set", "set chag")
nb.train("handle", "handle devices with ids")
nb.train("remove", "remove all subscriptions")
nb.train("send", "send roomie")
nb.train("verify", "verify manual entry")
nb.train("discover", "discover agents")
nb.train("get", "get agents")
nb.train("add", "add or update agent")
nb.train("get", "get uuid from usn")
nb.train("execute", "jawbone handler")
nb.train("set", "page about")
nb.train("set", "page uninstall")
nb.train("set", "page status")
nb.train("set", "page history")
nb.train("set", "page select zones")
nb.train("set", "page configure zones")
nb.train("set", "page arming options")
nb.train("set", "page alarm options")
nb.train("set", "page notifications")
nb.train("set", "page remote options")
nb.train("set", "page rest api options")
nb.train("if", "on contact")
nb.train("if", "on motion")
nb.train("if", "on movement")
nb.train("if", "on smoke")
nb.train("if", "on water")
nb.train("if", "on button event")
nb.train("activate", "activate alarm")
nb.train("set", "set summary")
nb.train("get", "get initial data")
nb.train("get", "get html")
nb.train("get", "get encored push")
nb.train("start", "start process ")
nb.train("start", "start day")
nb.train("if", "sched desc")
nb.train("create", "create day array")
nb.train("set", "set active and schedule")
nb.train("turn", "turn off motion after delay")
nb.train("continue", "continue flashing")
nb.train("set", "linker page")
nb.train("update", "update switch level")
nb.train("update", "update block level")
nb.train("update", "update switch state")
nb.train("update", "update block state")
nb.train("get", "get block id")
nb.train("get", "get linker description")
nb.train("set", "list page")
nb.train("set", "server page")
nb.train("set", "notifier page")
nb.train("set", "chat page")
nb.train("create", "create block")
nb.train("update", "update block")
nb.train("send", "send data block")
nb.train("delete", "delete block")
nb.train("if", "destroyed page")
nb.train("set", "redstone page")
nb.train("set", "neighbor block page")
nb.train("set", "message builder page")
nb.train("set", "page state complete")
nb.train("execute", "smart block destroyed handler")
nb.train("execute", "smart block neighbor changed handler")
nb.train("execute", "redstone signal strength handler")
nb.train("notify", "notify user of redstone change")
nb.train("notify", "notify user of neighbor change")
nb.train("notify", "notify user")
nb.train("set", "message description parts for page")
nb.train("set", "message description for page")
nb.train("get", "get message part from option")
nb.train("get", "get latest close player")
nb.train("convert", "convert block setting block id")
nb.train("if", "scheduled event")
nb.train("choose", "choose track")
nb.train("handle", "handle button")
nb.train("execute", "valve on handler")
nb.train("set", "set start time")
nb.train("start", "start page")
nb.train("set", "global page")
nb.train("set", "weather page")
nb.train("set", "zipcode page")
nb.train("set", "delay page")
nb.train("set", "zone page")
nb.train("set", "zone settings page")
nb.train("set", "zone set page")
nb.train("set", "plant set page")
nb.train("set", "sprinkler set page")
nb.train("set", "option set page")
nb.train("set", "set page")
nb.train("install", "install schedule")
nb.train("write", "write settings")
nb.train("write", "write cycles")
nb.train("sub", "sub off")
nb.train("if", "off pause check")
nb.train("send", "send it")
nb.train("set", "set season")
nb.train("get", "get rain today")
nb.train("get", "get dpw days")
nb.train("create", "create dpw map")
nb.train("execute", "goal handler")
nb.train("execute", "step handler")
nb.train("execute", "sunrise handler")
nb.train("execute", "sunset handler")
nb.train("get", "get pref")
nb.train("set", "page main")
nb.train("set", "page weather settings a")
nb.train("set", "page weather settings b")
nb.train("set", "page weather settings c")
nb.train("set", "page weather settings d")
nb.train("get", "get summary ")
nb.train("get", "get weather desc")
nb.train("get", "get gateway data")
nb.train("get", "get token")
nb.train("calculate", "calculate current power use")
nb.train("generate", "generate sha")
nb.train("debug", "debug out")
nb.train("remove", "remove child from settings")
nb.train("execute", "log handler")
nb.train("if", "on handler")
nb.train("if", "off handler")
nb.train("execute", "dim handler")
nb.train("if", "greyed out")
nb.train("if", "greyed out therm")
nb.train("if", "greyed out settings")
nb.train("add", "add contact subscription")
nb.train("remove", "remove contact sensor subscription")
nb.train("add", "add presence subscription")
nb.train("remove", "remove presence sensor subscription")
nb.train("add", "add switch subscription")
nb.train("remove", "remove switch subscription")
nb.train("add", "add motion subscription")
nb.train("remove", "remove motion subscription")
nb.train("add", "add lock subscription")
nb.train("remove", "remove lock subscription")
nb.train("execute", "motion open handler")
nb.train("get", "get data from wattvision")
nb.train("get", "get data for child")
nb.train("get", "get data")
nb.train("create", "create device")
nb.train("delete", "delete device")
nb.train("set", "set api access")
nb.train("revoke", "revoke api access")
nb.train("create", "create child")
nb.train("update", "update current weather")
nb.train("calculate", "calculate dew point")
nb.train("get", "get app info")
nb.train("get", "get loc")
nb.train("get", "get current report")
nb.train("set", "set temperature")
nb.train("get", "get or default")
nb.train("send", "send weather bug")
nb.train("get", "get wemo switches")
nb.train("get", "get wemo motions")
nb.train("get", "get wemo light switches")
nb.train("refresh", "refresh devices")
nb.train("subscribe", "subscribe devices")
nb.train("add", "add switches")
nb.train("add", "add motions")
nb.train("add", "add light switches")
nb.train("execute", "ssdp switch handler")
nb.train("execute", "ssdp motion handler")
nb.train("execute", "ssdp light switch handler")
nb.train("check", "check things")
nb.train("attach", "attach params")
nb.train("send", "send measure events")
nb.train("parse", "parse measure group")
nb.train("parse", "parse measure")
nb.train("fetch", "fetch data from withings")
nb.train("collect", "collect token from withings")
nb.train("get", "get consumer key")
nb.train("get", "get consumer secret")
nb.train("get", "get user id")
nb.train("if", "authorized html head")
nb.train("if", "authorized html body")
nb.train("build", "build oauth url with token")
nb.train("get", "get measurement")
nb.train("parse", "parse json")
nb.train("if", "save measurement")
nb.train("get", "get withings device")
nb.train("get", "get child namespace")
nb.train("get", "get scale child name")
nb.train("get", "get body analyzer child name")
nb.train("get", "get smart things consumer key")
nb.train("get", "get smart things consumer secret")
nb.train("build", "build url")
nb.train("get", "get server name")
nb.train("take", "take picture")
nb.train("set", "ha settings page")
nb.train("set", "set presence")
nb.train("execute", "mode handler")
nb.train("get", "get ct bright")
nb.train("get", "get hex")
nb.train("get", "get bright")
nb.train("switch", "switch off")
nb.train("execute", "motion evt handler")
nb.train("take", "take actions")
nb.train("ask", "ask alexa mq handler")
nb.train("reschedule", "reschedule if needed")
nb.train("set", "display tips page")
nb.train("get", "get custom image path")
nb.train("execute", "climate list handler")
nb.train("set", "set climate now")
nb.train("set", "set climate")
nb.train("if", "is right day for change")
nb.train("set", "set heating setpoint")
nb.train("execute", "thermostat mode handler")
nb.train("execute", "door unlocked handler")
nb.train("execute", "smoke handler")
nb.train("execute", "carbon monoxide handler")
nb.train("handle", "handle temperature event")
nb.train("handle", "handle humidity event")
nb.train("handle", "handle heating setpoint event")
nb.train("handle", "handle cooling setpoint event")
nb.train("handle", "handle thermostat mode event")
nb.train("handle", "handle fan mode event")
nb.train("handle", "handle humidifier mode event")
nb.train("handle", "handle humidifier level event")
nb.train("handle", "handle dehumidifier mode event")
nb.train("handle", "handle dehumidifier level event")
nb.train("handle", "handle ventilator mode event")
nb.train("handle", "handle fan min on time event")
nb.train("handle", "handle ventilator min on time event")
nb.train("handle", "handle thermostat operating state event")
nb.train("handle", "handle daily stats")
nb.train("handle", "handle equipment status event")
nb.train("handle", "handle program name event")
nb.train("handle", "handle water event")
nb.train("handle", "handle smoke event")
nb.train("handle", "handle carbon monoxide event")
nb.train("handle", "handle illuminance event")
nb.train("handle", "handle lock event")
nb.train("handle", "handle battery event")
nb.train("handle", "handle contact event")
nb.train("handle", "handle acceleration event")
nb.train("handle", "handle motion event")
nb.train("handle", "handle presence event")
nb.train("handle", "handle switch event")
nb.train("handle", "handle set level event")
nb.train("handle", "handle power event")
nb.train("handle", "handle energy event")
nb.train("handle", "handle cost event")
nb.train("if", "on light off")
nb.train("if", "on app touch")
nb.train("create", "create group")
nb.train("modify", "modify group")
nb.train("remove", "remove group")
nb.train("create", "create scene")
nb.train("modify", "modify scene")
nb.train("remove", "remove scene")
nb.train("get", "get hue bulbs")
nb.train("get", "get hue groups")
nb.train("get", "get hue scenes")
nb.train("execute", "bulb list handler")
nb.train("execute", "group list handler")
nb.train("execute", "scene list handler")
nb.train("add", "add groups")
nb.train("add", "add scenes")
nb.train("set", "set transition time ")
nb.train("set", "set group scene")
nb.train("set", "set group")
nb.train("get", "get id")
nb.train("update", "update scene from device")
nb.train("update", "update scene")
nb.train("rename", "rename scene")
nb.train("delete", "delete scene")
nb.train("create", "create new scene")
nb.train("update", "update group")
nb.train("rename", "rename group")
nb.train("delete", "delete group")
nb.train("create", "create new group")
nb.train("get", "get bridge dni")
nb.train("get", "get bridge hostname")
nb.train("get", "get bridge hostname and port")
nb.train("convert", "convert group list map")
nb.train("convert", "convert scene list map")
nb.train("get", "get selected transition")
nb.train("set", "set alert")
nb.train("set", "set effect")
nb.train("if", "is open")
nb.train("handle", "handle app touch")
nb.train("handle", "handle mode event")
nb.train("handle", "handle influx response")
nb.train("disable", "disable integration")
nb.train("enable", "enable integration")
nb.train("if", "authorized devices")
nb.train("configure", "configure bulbs")
nb.train("remove", "remove bulbs")
nb.train("update", "update grp")
nb.train("get", "get app version")
nb.train("set", "dashboard page")
nb.train("dehumidify", "dehumidify settings")
nb.train("set", "set humidity level")
nb.train("get", "get image path")
nb.train("get", "get app name")
nb.train("execute", "change mode handler")
nb.train("set", "set climate evt handler")
nb.train("execute", "program heat evt handler")
nb.train("execute", "program cool evt handler")
nb.train("execute", "lock handler")
nb.train("notify", "notify unlocked")
nb.train("get", "get clusters")
nb.train("enroll", "enroll response")
nb.train("parse", "parse description as map")
nb.train("update", "update state")
nb.train("set", "set model")
nb.train("set", "set local level")
nb.train("get", "get group status")
nb.train("set", "set play mode")
nb.train("play", "play text and resume")
nb.train("play", "play track and resume")
nb.train("play", "play text and restore")
nb.train("play", "play track and restore")
nb.train("play", "play text and track")
nb.train("play", "play sound and track")
nb.train("play", "play track at volume")
nb.train("play", "play track")
nb.train("set", "set track")
nb.train("resume", "resume track")
nb.train("restore", "restore track")
nb.train("play", "play text")
nb.train("set", "set text")
nb.train("get", "get volume")
nb.train("get", "get current media")
nb.train("get", "get current status")
nb.train("get", "get system string")
nb.train("set", "set color hex")
nb.train("get", "get current level")
nb.train("get", "get verifiedstriim light player")
nb.train("if", "scheduled refresh handler")
nb.train("if", "scheduled actions handler")
nb.train("get", "get data by name")
nb.train("add", "add child app ")
nb.train("add", "add child device ")
nb.train("create", "create access token ")
nb.train("find", "find all child apps by name ")
nb.train("find", "find all child apps by namespace and name ")
nb.train("find", "find child app by name ")
nb.train("find", "find child app by namespace and name ")
nb.train("get", "get all child apps ")
nb.train("get", "get child apps ")
nb.train("delete", "delete child device ")
nb.train("get", "get all child devices ")
nb.train("get", "get api server url ")
nb.train("get", "get child device ")
nb.train("get", "get child devices ")
nb.train("get", "get color util ")
nb.train("get", "get location ")
nb.train("get", "get sunrise and sunset ")
nb.train("get", "get twc conditions ")
nb.train("get", "get twc forecast ")
nb.train("get", "get twc location ")
nb.train("get", "get twc alerts ")
nb.train("get", "get twc alert detail ")
nb.train("get", "get weather feature -  deprecated ")
nb.train("http", "http delete ")
nb.train("parse", "parse json ")
nb.train("parse", "parse xml ")
nb.train("parse", "parse lan message ")
nb.train("parse", "parse soap message ")
nb.train("revoke", "revoke access token ")
nb.train("if", "run in ")
nb.train("run", "run every1 minute ")
nb.train("run", "run every5 minutes ")
nb.train("run", "run every10 minutes ")
nb.train("run", "run every15 minutes ")
nb.train("run", "run every30 minutes ")
nb.train("run", "run every1 hour ")
nb.train("run", "run every3 hours ")
nb.train("run", "run once ")
nb.train("send", "send event ")
nb.train("send", "send hub command ")
nb.train("send", "send location event ")
nb.train("send", "send notification ")
nb.train("send", "send notification event ")
nb.train("send", "send notification contacts ")
nb.train("send", "send push ")
nb.train("send", "send push message ")
nb.train("send", "send sms ")
nb.train("send", "send sms message ")
nb.train("set", "set location mode ")
nb.train("subscribe", "subscribe command ")
nb.train("add", "add child device ")
nb.train("create", "create event ")
nb.train("get", "get api server url ")
nb.train("get", "get child devices ")
nb.train("get", "get color util ")
nb.train("get", "get image ")
nb.train("http", "http delete ")
nb.train("run", "run every1 minute ")
nb.train("run", "run every5 minutes ")
nb.train("run", "run every10 minutes ")
nb.train("run", "run every15 minutes ")
nb.train("run", "run every30 minutes ")
nb.train("run", "run every1 hour ")
nb.train("run", "run every3 hours ")
nb.train("if", "run in ")
nb.train("run", "run once ")
nb.train("send", "send event ")
nb.train("get", "get date value ")
nb.train("get", "get id ")
nb.train("get", "get description text ")
nb.train("get", "get double value ")
nb.train("get", "get float value ")
nb.train("get", "get integer value ")
nb.train("get", "get iso date ")
nb.train("get", "get json value ")
nb.train("get", "get last updated ")
nb.train("get", "get long value ")
nb.train("get", "get name ")
nb.train("get", "get number value ")
nb.train("get", "get numeric value ")
nb.train("get", "get unit ")
nb.train("get", "get value ")
nb.train("get", "get xyz value ")
nb.train("get", "get data ")
nb.train("get", "get error data ")
nb.train("get", "get error json ")
nb.train("get", "get error message ")
nb.train("get", "get error xml ")
nb.train("get", "get headers ")
nb.train("get", "get json ")
nb.train("get", "get status ")
nb.train("get", "get warning messages ")
nb.train("get", "get xml ")
nb.train("if", "has error ")
nb.train("get", "get data type ")
nb.train("get", "get name ")
nb.train("get", "get values ")
nb.train("get", "get attributes ")
nb.train("get", "get commands ")
nb.train("get", "get name ")
nb.train("get", "get arguments ")
nb.train("get", "get name ")
nb.train("get", "get capabilities ")
nb.train("get", "get device network id ")
nb.train("get", "get display name ")
nb.train("get", "get hub ")
nb.train("get", "get id ")
nb.train("get", "get label ")
nb.train("get", "get last activity ")
nb.train("get", "get manufacturer name ")
nb.train("get", "get model name ")
nb.train("get", "get status ")
nb.train("get", "get name ")
nb.train("get", "get supported attributes ")
nb.train("get", "get supported commands ")
nb.train("get", "get type name ")
nb.train("if", "has attribute ")
nb.train("if", "has capability ")
nb.train("if", "has command ")
nb.train("get", "get data ")
nb.train("get", "get date ")
nb.train("get", "get date value ")
nb.train("get", "get description ")
nb.train("get", "get description text ")
nb.train("get", "get device ")
nb.train("get", "get display name ")
nb.train("get", "get device id ")
nb.train("get", "get id ")
nb.train("get", "get double value ")
nb.train("get", "get float value ")
nb.train("get", "get hub id ")
nb.train("get", "get installed smart app id ")
nb.train("get", "get integer value ")
nb.train("get", "get iso date ")
nb.train("get", "get json value ")
nb.train("get", "get link text ")
nb.train("get", "get location ")
nb.train("get", "get location id ")
nb.train("get", "get long value ")
nb.train("get", "get name ")
nb.train("get", "get number value ")
nb.train("get", "get numeric value ")
nb.train("get", "get source ")
nb.train("get", "get string value ")
nb.train("get", "get unit ")
nb.train("get", "get value ")
nb.train("get", "get xyz value ")
nb.train("if", "is digital ")
nb.train("if", "is physical ")
nb.train("if", "is state change ")
nb.train("get", "get firmware version string ")
nb.train("get", "get id ")
nb.train("get", "get local ip ")
nb.train("get", "get local srv port tcp ")
nb.train("get", "get name ")
nb.train("get", "get type ")
nb.train("get", "get zigbee eui ")
nb.train("get", "get zigbee id ")
nb.train("get", "get account id ")
nb.train("get", "get all child apps ")
nb.train("get", "get app settings ")
nb.train("get", "get child apps ")
nb.train("get", "get child devices ")
nb.train("get", "get execution is mode restricted ")
nb.train("get", "get executable modes ")
nb.train("get", "get id ")
nb.train("get", "get installation state ")
nb.train("get", "get label ")
nb.train("get", "get name ")
nb.train("get", "get namespace ")
nb.train("get", "get parent ")
nb.train("get", "get subscriptions ")
nb.train("update", "update label ")
nb.train("get", "get contact book enabled ")
nb.train("get", "get current mode ")
nb.train("get", "get id ")
nb.train("get", "get hubs ")
nb.train("get", "get latitude ")
nb.train("get", "get longitude ")
nb.train("get", "get mode ")
nb.train("get", "get modes ")
nb.train("get", "get name ")
nb.train("set", "set mode ")
nb.train("get", "get temperature scale ")
nb.train("get", "get time zone ")
nb.train("get", "get zip code ")
nb.train("get", "get id ")
nb.train("get", "get name ")
nb.train("get", "get date ")
nb.train("get", "get date value ")
nb.train("get", "get double value ")
nb.train("get", "get float value ")
nb.train("get", "get id")
nb.train("get", "get integer value")
nb.train("get", "get iso date")
nb.train("get", "get json value")
nb.train("get", "get long value")
nb.train("get", "get name")
nb.train("get", "get number value")
nb.train("get", "get numeric value")
nb.train("get", "get string value")
nb.train("get", "get unit")
nb.train("get", "get value")
nb.train("get", "get xyz value")
nb.train("o", "installed")
nb.train("o", "updated")
nb.train("list", "list switches")
nb.train("show", "show switch")
nb.train("list", "list locks")
nb.train("show", "show lock")
nb.train("o", "uninstalled")
nb.train("o", "initialize")
nb.train("set", "main page")
nb.train("execute", "beacon handler")
nb.train("if", "app touch")
nb.train("if", "presence")
nb.train("run", "device discovery")
nb.train("execute", "bose zone join")
nb.train("execute", "bose zone reset")
nb.train("if", "bose zone has master")
nb.train("execute", "bose zone leave")
nb.train("parse", "parse ssdp")
nb.train("execute", "event handler")
nb.train("execute", "mode change handler")
nb.train("execute", "app touch handler")
nb.train("set", "configurations")
nb.train("set", "options")
nb.train("if", "location position change")
nb.train("execute", "sunrise sunset time handler")
nb.train("execute", "motion handler")
nb.train("execute", "lights handler")
nb.train("execute", "dimmers handler")
nb.train("execute", "illuminance handler")
nb.train("execute", "astro check")
nb.train("execute", "contact open handler")
nb.train("execute", "motion active handler")
nb.train("select ", "select button")
nb.train("set", "configured")
nb.train("set", "button configured")
nb.train("execute", "button event")
nb.train("o", "find")
nb.train("o", "toggle")
nb.train("change", "change mode")
nb.train("if", "rider is home")
nb.train("execute", "water handler")
nb.train("run", "coffee maker")
nb.train("o", "init")
nb.train("execute", "color handler")
nb.train("execute", "temp handler")
nb.train("get", "index")
nb.train("if", "motion active")
nb.train("if", "motion inactive")
nb.train("if", "not present")
nb.train("if", "all quiet")
nb.train("if", "any here")
nb.train("if", "outlets on")
nb.train("if", "outlets off")
nb.train("execute", "motion inactive handler")
nb.train("set", "default page")
nb.train("get", "label map")
nb.train("execute", "coop door state handler")
nb.train("if", "door closed")
nb.train("if", "door knock")
nb.train("execute", "switch handler")
nb.train("set", "auth page")
nb.train("oauth", "oauth init url")
nb.train("run", "callback")
nb.train("if", "success")
nb.train("if", "fail")
nb.train("get", "connection status")
nb.train("execute", "poll handler")
nb.train("poll", "poll children")
nb.train("poll", "poll child")
nb.train("get", "available modes")
nb.train("get", "current mode")
nb.train("get", "json")
nb.train("get", "query string")
nb.train("run", "schedule check")
nb.train("if", "bedroom active")
nb.train("if", "bathroom active")
nb.train("execute", "meter handler")
nb.train("lock", "lock door")
nb.train("unlock", "unlock door")
nb.train("execute", "door handler")
nb.train("set", "first page")
nb.train("set", "input page")
nb.train("set", "input boolean page")
nb.train("set", "input icon page")
nb.train("set", "input image page")
nb.train("set", "options group")
nb.train("list", "list map")
nb.train("set", "input selection page")
nb.train("set", "input text page")
nb.train("set", "input time page")
nb.train("set", "input device page")
nb.train("set", "input capability page")
nb.train("set", "input room page")
nb.train("set", "input mode page")
nb.train("set", "input hub page")
nb.train("set", "input contact book page")
nb.train("set", "app page")
nb.train("set", "label page")
nb.train("set", "paragraph page")
nb.train("set", "href page")
nb.train("set", "buttons page")
nb.train("set", "image page")
nb.train("set", "video page")
nb.train("undefined", "foo")
nb.train("execute", "water wet handler")
nb.train("raise", "trigger alarm")
nb.train("raise", "fire alarm")
nb.train("run", "camera discovery")
nb.train("login", "foscam")
nb.train("if", "cameras discovered")
nb.train("execute", "location handler")
nb.train("execute", "acceleration handler")
nb.train("clear", "clear sms history")
nb.train("clear", "clear status")
nb.train("set", "root page")
nb.train("set", "unsupported devices page")
nb.train("set", "controller explanation page")
nb.train("set", "numbers page")
nb.train("run", "default start")
nb.train("run", "default end")
nb.train("get", "end level label")
nb.train("if", "weekdays")
nb.train("if", "weekends")
nb.train("o", "speak")
nb.train("if", "can start automatically")
nb.train("get", "completion percentage")
nb.train("get", "time remaining")
nb.train("o", "jump to")
nb.train("get", "fancy string")
nb.train("get", "fancy device string")
nb.train("get", "device label")
nb.train("get", "scheduling href description")
nb.train("get", "completion href description")
nb.train("get", "hue sat hex")
nb.train("get", "hsl rgb")
nb.train("get", "rgb hex")
nb.train("if", "uses old settings")
nb.train("open", "open garage")
nb.train("close", "close garage")
nb.train("open", "open shade")
nb.train("preset", "preset shade")
nb.train("close", "close shade")
nb.train("lock", "lock door lock")
nb.train("unlock", "unlock door lock")
nb.train("take", "hello actions")
nb.train("get", "structure info")
nb.train("acquire", "acquire data")
nb.train("if", "lights out")
nb.train("if", "door opened")
nb.train("set", "page with ip")
nb.train("run", "bridge discovery")
nb.train("if", "bridge discovery failed")
nb.train("run", "bridge linking")
nb.train("run", "bulb discovery")
nb.train("execute", "manual refresh")
nb.train("o", "parse")
nb.train("execute", "hub verification")
nb.train("turn", "on")
nb.train("turn", "off")
nb.train("get", "hex hsv")
nb.train("get", "hsv hex")
nb.train("o", "list")
nb.train("list", "list states")
nb.train("list", "list subscriptions")
nb.train("o", "update")
nb.train("o", "show")
nb.train("send", "send it")
nb.train("set", "setup")
nb.train("response", "response goals")
nb.train("response", "response moves")
nb.train("check", "check server")
nb.train("handle", "event")
nb.train("o", "subscribe")
nb.train("open", "door open")
nb.train("if", "door open too long")
nb.train("test", "test life connection")
nb.train("list", "list circles ")
nb.train("list", "list places")
nb.train("list", "list users ")
nb.train("get", "haversine")
nb.train("get", "apiurl")
nb.train("oauth", "oauth init")
nb.train("oauth", "oauth callback")
nb.train("oauth", "oauth receive token")
nb.train("oauth", "oauth success")
nb.train("oauth", "oauth failure")
nb.train("oauth", "oauth received token")
nb.train("oauth", "oauth connection status")
nb.train("log", "log response")
nb.train("log", "log errors")
nb.train("get", "api get")
nb.train("put", "api put")
nb.train("get", "devices list")
nb.train("get", "devices in location")
nb.train("set", "page setup")
nb.train("set", "page setup scenario a")
nb.train("set", "page setup scenario b")
nb.train("set", "page setup scenario c")
nb.train("set", "page setup scenario d")
nb.train("delay", "delay turn off a")
nb.train("delay", "delay turn off b")
nb.train("delay", "delay turn off c")
nb.train("delay", "delay turn off d")
nb.train("run", "mid night reset")
nb.train("grey", "grey out")
nb.train("run", "door open check")
nb.train("lock", "lock message")
nb.train("run", "discovery")
nb.train("run", "activity")
nb.train("get", "activity response")
nb.train("o", "poll")
nb.train("get", "poll response")
nb.train("list", "list devices")
nb.train("list", "list phrases")
nb.train("list", "list hubs")
nb.train("get", "activity callback")
nb.train("run", "harmony")
nb.train("check", "check motion in past")
nb.train("check", "check motion after reminder")
nb.train("toggle", "toggle switches")
nb.train("get", "api get")
nb.train("get", "c pref")
nb.train("get", "rain pref")
nb.train("set", "page two")
nb.train("change", "change sun mode")
nb.train("register", "register device change")
nb.train("unregister", "unregister device change")
nb.train("register", "register device graph")
nb.train("unregister", "unregister device graph")
nb.train("get", "dock sensor")
nb.train("check", "check and update plant if needed")
nb.train("swap", "swap token")
nb.train("run", "subscriber identify verification")
nb.train("put", "api put")
nb.train("o", "c f")
nb.train("o", "f c")
nb.train("dollarize", "dollarize")
nb.train("poll", "poll nimbus")
nb.train("poll", "poll outlet")
nb.train("get", "car presence")
nb.train("get", "garage door contact")
nb.train("if", "interior door closed")
nb.train("if", "acceleration active")
nb.train("select", "select routines")
nb.train("check", "check sun")
nb.train("triggertrigger", "trigger contact")
nb.train("", "trigger motion")
nb.train("trigger", "trigger knock")
nb.train("trigger", "trigger temp")
nb.train("trigger", "trigger axis")
nb.train("schedule", "schedule job")
nb.train("check", "check for severe weather")
nb.train("run", "description filter")
nb.train("if", "location is defined")
nb.train("if", "zipcode is valid")
nb.train("get", "hebcal  web request")
nb.train("get", "new  date")
nb.train("get", "get weather feature")
nb.train("get", "get time")
nb.train("run", "agent discovery")
nb.train("run", "manual agent entry")
nb.train("if", "agents discovered")
nb.train("get", "geturn")
nb.train("convert", "convert hex ip")
nb.train("convert", "convert hex int")
nb.train("convert", "convert hex string")
nb.train("convert", "convert ip hex string")
nb.train("if", "can install labs")
nb.train("if", "has all hubs over")
nb.train("get", "get real hub firmware versions")
nb.train("run", "agent selection")
nb.train("o", "control")
nb.train("select", "select phrases")
nb.train("set", "page about")
nb.train("set", "page uninstall")
nb.train("set", "page status")
nb.train("set", "page history")
nb.train("set", "page select zones")
nb.train("set", "page configure zones")
nb.train("set", "page arming options")
nb.train("set", "page alarm options")
nb.train("set", "page notifications")
nb.train("set", "page remote options")
nb.train("set", "page rest api options")
nb.train("arm", "arm away")
nb.train("arm", "arm stay")
nb.train("disarm", "disarm")
nb.train("get", "panic")
nb.train("run", "reset")
nb.train("exit", "exit delay expired")
nb.train("arm", "api arm away")
nb.train("arm", "api arm stay")
nb.train("disarm", "api disarm")
nb.train("get", "api panic")
nb.train("get", "api status")
nb.train("get", "white list")
nb.train("check", "check access token")
nb.train("if", "request code")
nb.train("get", "console log")
nb.train("if", "inc day")
nb.train("if", "mid night")
nb.train("change", "switch change")
nb.train("get", "motion")
nb.train("get", "intruder motion")
nb.train("get", "resident motion")
nb.train("get", "contact")
nb.train("raise", "alarm")
nb.train("check", "check for re arm")
nb.train("raise", "sound siren")
nb.train("check", "weather check")
nb.train("chat", "chat message mc")
nb.train("o", "ack")
nb.train("run", "smart phone notification section")
nb.train("run", "chat section")
nb.train("run", "message builder section")
nb.train("run", "message builder href")
nb.train("chat", "chat closest player section")
nb.train("complete", "page state complete")
nb.train("set", "message parts set")
nb.train("get", "default message description")
nb.train("get", "message part default value")
nb.train("send", "message")
nb.train("set", "message builder options")
nb.train("set", "settings as ids")
nb.train("if", "all blocks parsed")
nb.train("get", "all blocks")
nb.train("extract", "extract button number")
nb.train("toggle", "toggle play pause")
nb.train("adjust", "adjust volume")
nb.train("get", "open valve")
nb.train("get", "close valve")
nb.train("run", "manual start")
nb.train("if", "busy off")
nb.train("run", "pre check")
nb.train("turn", "cycle on")
nb.train("turn", "cycle off")
nb.train("check", "check run map")
nb.train("run", "cycle loop")
nb.train("o", "resume")
nb.train("turn", "sync on")
nb.train("stop", "water stop")
nb.train("start", "water start")
nb.train("get", "moisture")
nb.train("get", "note")
nb.train("send", "setup notifications")
nb.train("send", "lights notification")
nb.train("send", "hue notification")
nb.train("send", "sonos notification")
nb.train("set", "page main")
nb.train("set", "page weather settings a")
nb.train("set", "page weather settings b")
nb.train("set", "page weather settings c")
nb.train("set", "page weather settings d")
nb.train("raise", "alarm a")
nb.train("raise", "alarm b")
nb.train("raise", "alarm c")
nb.train("raise", "alarm d")
nb.train("set", "grey out option")
nb.train("get", "dimmer desc")
nb.train("get", "thermostat desc")
nb.train("unin]", "uninstall from child device")
nb.train("set", "setup bulbs")
nb.train("post", "api post")
nb.train("generate", "generatemd")
nb.train("check", "check devices online")
nb.train("syncronize", "syncronize devices")
nb.train("poll", "poll room")
nb.train("login", "login tesla")
nb.train("select", "select cars")
nb.train("get", "get car list")
nb.train("change", "sensor change")
nb.train("o", "restore")
nb.train("set", "director settings")
nb.train("run", "thermostat and doors")
nb.train("run", "thermostat boost")
nb.train("set", "settings")
nb.train("change", "mode boost change")
nb.train("trigger", "thermo shut off trigger")
nb.train("shut", "thermo shut off")
nb.train("check", "door check")
nb.train("change", "thermo change")
nb.train("change", "window change")
nb.train("list", "list all")
nb.train("list", "list contact sensors")
nb.train("show", "show contact sensor")
nb.train("list", "list presence sensors")
nb.train("show", "show presence sensor")
nb.train("list", "list motions")
nb.train("show", "show motion")
nb.train("get", "current state")
nb.train("show", "show states")
nb.train("list", "list phrases with type")
nb.train("set", "setup")
nb.train("input", "time interval input")
nb.train("list", "list all devices")
nb.train("o", "wattvisionurl")
nb.train("get", "child marshaller")
nb.train("schedule", "schedule data collection")
nb.train("login", "login callback")
nb.train("if", "connection successful")
nb.train("push", "push latest")
nb.train("if", "devices discovered")
nb.train("if", "switches discovered")
nb.train("if", "motions discovered")
nb.train("if", "light switches discovered")
nb.train("o", "resubscribe")
nb.train("run", "refresh")
nb.train("run", "test")
nb.train("o", "authenticate")
nb.train("exchange", "exchange token from withings")
nb.train("if", "notification received")
nb.train("get", "st base url")
nb.train("get", "st token")
nb.train("get", "short url")
nb.train("get", "no token url")
nb.train("get", "unix time")
nb.train("execute", "backfill measures")
nb.train("get", "w get measures")
nb.train("get", "measure value")
nb.train("get", "w notification base url")
nb.train("get", "w notification callback url")
nb.train("get", "w get notification")
nb.train("create", "w create notification")
nb.train("revoke", "w revoke all notifications")
nb.train("revoke", "w revoke notification")
nb.train("list", "w list notifications")
nb.train("get", "default oauth params")
nb.train("if", "w log enabled")
nb.train("request", "request token url")
nb.train("get", "user authorization url")
nb.train("exchange", "exchange token url")
nb.train("exchange", "exchange token")
nb.train("get", "default parameter keys")
nb.train("oauth", "oauth consumer key")
nb.train("oauth", "oauth nonce")
nb.train("o", "nonce")
nb.train("oauth", "oauth signature method")
nb.train("oauth", "oauth timestamp")
nb.train("oauth", "oauth version")
nb.train("oauth", "oauth callback")
nb.train("oauth", "oauth token")
nb.train("oauth", "oauth token secret")
nb.train("get", "userid")
nb.train("take", "render action")
nb.train("get", "not authorized html head")
nb.train("get", "not authorized html body")
nb.train("load", "load")
nb.train("check", "measurement error")
nb.train("get", "event value")
nb.train("handle", "withings event")
nb.train("if", "should poll")
nb.train("take", "config actions")
nb.train("check", "check presence")
nb.train("list", "list available cameras")
nb.train("o", "foauth")
nb.train("o", "authorize")
nb.train("handle", "zwave event")
nb.train("exchange", "configuration cmds")
nb.train("set", "configure")
nb.train("if", "status changed")
nb.train("if", "contact triggered")
nb.train("if", "motion triggered")
nb.train("if", "sensor triggered")
nb.train("select", "select alarm")
nb.train("select", "select sensors")
nb.train("select", "select states")
nb.train("set", "other settings")
nb.train("if", "arrived")
nb.train("o", "left")
nb.train("execute", "handler")
nb.train("flush", "flush buffer")
nb.train("generate", "generate url")
nb.train("view", "view url")
nb.train("schedule", "schedule turn on")
nb.train("get", "get ct")
nb.train("get", "get hsv")
nb.train("get", "ct rgb")
nb.train("get", "rgb hsv")
nb.train("config", "config app")
nb.train("alarm", "alarm switch contact")
nb.train("select", "select program")
nb.train("select", "select modes")
nb.train("change", "change fan min on time")
nb.train("clear", "clear heating setpoint")
nb.train("set", "actions settings")
nb.train("clear", "clear alert")
nb.train("run", "switch hit")
nb.train("process", "process queue")
nb.train("change", "change color")
nb.train("o", "start")
nb.train("o", "stop")
nb.train("run", "group discovery")
nb.train("run", "scene discovery")
nb.train("change", "change scene name")
nb.train("complete", "init complete")
nb.train("execute", "default transition")
nb.train("get", "next level")
nb.train("get", "ip address from dni")
nb.train("execute", "soft poll")
nb.train("log", "log system properties")
nb.train("post", "post influx db")
nb.train("copy", "copy config")
nb.train("render", "render config")
nb.train("get", "device command map")
nb.train("render", "render devices")
nb.train("execute", "device command")
nb.train("check", "auth error")
nb.train("get", "basic info")
nb.train("turn", "all off")
nb.train("select", "select things")
nb.train("o", "tick")
nb.train("get", "webhook")
nb.train("set", "sensor settings")
nb.train("set", "humidify settings")
nb.train("set", "ventilator settings")
nb.train("set", "temp sensor settings")
nb.train("set", "motion sensor settings")
nb.train("set", "threshold settings")
nb.train("monitor", "monitor adjust temp")
nb.train("o", "identify")
nb.train("check", "check door")
nb.train("push", "button push")
nb.train("get", "tile set level")
nb.train("o", "play")
nb.train("o", "pause")
nb.train("get", "next track")
nb.train("get", "previous track")
nb.train("o", "seek")
nb.train("o", "mute")
nb.train("o", "unmute")
nb.train("o", "unsubscribe")
nb.train("o", "white")
nb.train("cycle", "cycle colors")
nb.train("run", "striim light discovery")
nb.train("get", "get striim light player")
nb.train("add", "add striim light")
nb.train("select", "select switches")
nb.train("o", "push")
nb.train("o", "hold")
nb.train("o", "release")
nb.train("associate", "associate hub")
nb.train("get", "integer")
nb.train("get", "integerhex")
nb.train("o", "installed")
nb.train("o", "updated")
nb.train("o", "uninstalled")
nb.train("get", "api server url")
nb.train("if", "can schedule")
nb.train("check", "http error")
nb.train("get", "http get")
nb.train("get", "http head")
nb.train("post", "http post")
nb.train("post", "http post json")
nb.train("put", "http put")
nb.train("put", "http put json")
nb.train("get", "next occurrence")
nb.train("if", "now")
nb.train("o", "render")
nb.train("o", "schedule")
nb.train("get", "string map")
nb.train("o", "subscribe")
nb.train("if", "time of day is between")
nb.train("if", "time offset")
nb.train("if", "time today")
nb.train("if", "time today after")
nb.train("get", "time zone")
nb.train("get", "date time")
nb.train("o", "unschedule")
nb.train("o", "unsubscribe")
nb.train("o", "parse")
nb.train("get", "api server url")
nb.train("get", "attribute")
nb.train("get", "capability")
nb.train("get", "carousel tile")
nb.train("get", "child device tile")
nb.train("execute", "command")
nb.train("control", "control tile")
nb.train("get", "definition")
nb.train("get", "details")
nb.train("get", "fingerprint")
nb.train("get", "http get")
nb.train("get", "http head")
nb.train("post", "http post")
nb.train("post", "http post json")
nb.train("put", "http put")
nb.train("put", "http put json")
nb.train("run", "main")
nb.train("get", "metadata")
nb.train("o", "reply")
nb.train("o", "schedule")
nb.train("run", "simulator")
nb.train("get", "standard tile")
nb.train("get", "state")
nb.train("get", "status")
nb.train("store", "store image")
nb.train("store", "store temporary image")
nb.train("get", "tiles")
nb.train("get", "value tile")
nb.train("o", "delete")
nb.train("o", "get")
nb.train("get", "head")
nb.train("o", "patch")
nb.train("o", "post")
nb.train("o", "put")
nb.train("get", "hex rgb")
nb.train("get", "rgb hex")
nb.train("get", "current state")
nb.train("get", "current value")
nb.train("handle", "events")
nb.train("o", "events between")
nb.train("o", "events since")
nb.train("get", "latest state")
nb.train("get", "latest value")
nb.train("o", "states between")
nb.train("o", "states since")
nb.train("get", "current state")
nb.train("o", "states between")
nb.train("o", "states since")



print(nb.classify("open the door"))

