# s for set
# g for get
# i for if
# e for execute
# t for turn
# o for others/no need verb
# maybe more tabs

nb.train("o", "installed")
nb.train("o", "updated")
nb.train("o", "list switches")
nb.train("o", "show switch")
nb.train("o", "list locks")
nb.train("o", "show lock")
nb.train("o", "validate command")
nb.train("g", "get capability name")
nb.train("g", "get device capability commands")
nb.train("e", "execute command")
nb.train("o", "uninstalled")
nb.train("o", "initialize")
nb.train("e", "handle things")
nb.train("s", "set fans")
nb.train("s", "main page")
nb.train("e", "beacon handler")
nb.train("i", "changed location mode")
nb.train("i", "app touch")
nb.train("i", "presence")
nb.train("o", "take action")
nb.train("g", "get device type")
nb.train("", "get usn qualifier")
nb.train("", "get device name")
nb.train("", "get name space")
nb.train("", "device discovery")
nb.train("", "add device")
nb.train("", "resolve dni address")
nb.train("", "bose zone join")
nb.train("", "bose zone reset")
nb.train("", "bose zone has master")
nb.train("", "bose zone leave")
nb.train("", "get parsers")
nb.train("", "on location")
nb.train("", "parsessdp")
nb.train("", "get verified devices")
nb.train("", "get devices")
nb.train("", "subscribe to events")
nb.train("", "event handler")
nb.train("", "mode change handler")
nb.train("", "scheduled time handler")
nb.train("", "app touch handler")
nb.train("", "configurations")
nb.train("", "options")
nb.train("", "location position change")
nb.train("", "sunrise sunset time handler")
nb.train("", "motion handler")
nb.train("", "lights handler")
nb.train("", "dimmers handler")
nb.train("", "illuminance handler")
nb.train("", "turn on lights")
nb.train("", "turn on dimmers")
nb.train("", "turn off lights")
nb.train("", "turn off dimmers")
nb.train("", "astro check")
nb.train("", "contact open handler")
nb.train("", "motion active handler")
nb.train("", "select button")
nb.train("", "configure button")
nb.train("", "get button sections")
nb.train("", "configured")
nb.train("", "button configured")
nb.train("", "button event")
nb.train("", "execute handlers")
nb.train("", "find")
nb.train("", "find msg")
nb.train("", "toggle")
nb.train("", "change mode")
nb.train("", "turn on camera")
nb.train("", "turn off camera")
nb.train("", "turn off")
nb.train("", "turn on")
nb.train("", "rider is home")
nb.train("", "send text")
nb.train("", "water handler")
nb.train("", "coffee maker")
nb.train("", "init")
nb.train("", "on off handler")
nb.train("", "color handler")
nb.train("", "get random color master")
nb.train("", "temp handler")
nb.train("", "index")
nb.train("", "motion active")
nb.train("", "motion inactive")
nb.train("", "not present")
nb.train("", "all quiet")
nb.train("", "any here")
nb.train("", "outlets on")
nb.train("", "outlets off")
nb.train("", "scheduled turn off")
nb.train("", "motion inactive handler")
nb.train("", "default page")
nb.train("", "initialize devices")
nb.train("", "label map")
nb.train("", "coop door state handler")
nb.train("", "door closed")
nb.train("", "door knock")
nb.train("", "handle event")
nb.train("", "switch handler")
nb.train("", "auth page")
nb.train("", "oauth init url")
nb.train("", "callback")
nb.train("", "success")
nb.train("", "fail")
nb.train("", "connection status")
nb.train("", "get ecobee thermostats")
nb.train("", "get thermostat display name")
nb.train("", "get thermostat type name")
nb.train("", "poll handler")
nb.train("", "poll children")
nb.train("", "poll child")
nb.train("", "available modes")
nb.train("", "current mode")
nb.train("", "update sensor data")
nb.train("", "get child device ids string")
nb.train("", "to json")
nb.train("", "to query string")
nb.train("", "get child name")
nb.train("", "get sensor child name")
nb.train("", "get server url")
nb.train("", "get shard url")
nb.train("", "get callback url")
nb.train("", "get build redirect url")
nb.train("", "get api endpoint")
nb.train("", "get smart things client id")
nb.train("", "debug event")
nb.train("", "send push and feeds")
nb.train("", "send activity feeds")
nb.train("", "convert fto c ")
nb.train("", "schedule check")
nb.train("", "bedroom active")
nb.train("", "bathroom active")
nb.train("", "send message")
nb.train("", "meter handler")
nb.train("", "lock door")
nb.train("", "unlock door")
nb.train("", "door handler")
nb.train("", "first page")
nb.train("", "input page")
nb.train("", "input boolean page")
nb.train("", "input icon page")
nb.train("", "input image page")
nb.train("", "options group")
nb.train("", "add values")
nb.train("", "list to map")
nb.train("", "add group")
nb.train("", "input selection page")
nb.train("", "input text page")
nb.train("", "input time page")
nb.train("", "input device page")
nb.train("", "input capability page")
nb.train("", "input room page")
nb.train("", "input mode page")
nb.train("", "input hub page")
nb.train("", "input contact book page")
nb.train("", "app page")
nb.train("", "label page")
nb.train("", "mode page")
nb.train("", "paragraph page")
nb.train("", "href page")
nb.train("", "buttons page")
nb.train("", "image page")
nb.train("", "video page")
nb.train("", "flattened page")
nb.train("", "foo")
nb.train("", "water wet handler")
nb.train("", "trigger alarm")
nb.train("", "fire alarm")
nb.train("", "camera discovery")
nb.train("", "login to foscam")
nb.train("", "cameras discovered")
nb.train("", "get cameras")
nb.train("", "add cameras")
nb.train("", "get device info")
nb.train("", "location handler")
nb.train("", "acceleration handler")
nb.train("", "send text message")
nb.train("", "update sms history")
nb.train("", "clear sms history")
nb.train("", "clear status")
nb.train("", "on command")
nb.train("", "root page")
nb.train("", "unsupported devices page")
nb.train("", "controller explanation page")
nb.train("", "numbers page")
nb.train("", "default start")
nb.train("", "default end")
nb.train("", "start level label")
nb.train("", "end level label")
nb.train("", "weekdays")
nb.train("", "weekends")
nb.train("", "scheduling page")
nb.train("", "completion page")
nb.train("", "app handler")
nb.train("", "stop dimmers handler")
nb.train("", "scheduled start")
nb.train("", "send start event")
nb.train("", "send stop event")
nb.train("", "send time remaining event")
nb.train("", "send controller event")
nb.train("", "get controller")
nb.train("", "update dimmers")
nb.train("", "speak")
nb.train("", "resume playing")
nb.train("", "set levels in state")
nb.train("", "can start automatically")
nb.train("", "completion percentage")
nb.train("", "time remaining")
nb.train("", "jump to")
nb.train("", "get hue")
nb.train("", "get up hue")
nb.train("", "get down hue")
nb.train("", "fancy string")
nb.train("", "fancy device string")
nb.train("", "device label")
nb.train("", "scheduling href description")
nb.train("", "completion href description")
nb.train("", "numbers page href description")
nb.train("", "hue sat to hex")
nb.train("", "hsl to rgb")
nb.train("", "rgb to hex")
nb.train("", "uses old settings")
nb.train("", "has start level")
nb.train("", "has end level")
nb.train("", "get all devices")
nb.train("", "set cool temp")
nb.train("", "set heat temp")
nb.train("", "set fan mode")
nb.train("", "set thermostat mode")
nb.train("", "get thermostat status")
nb.train("", "turn on light")
nb.train("", "turn off light")
nb.train("", "get light status")
nb.train("", "set color")
nb.train("", "get color status")
nb.train("", "set kelvin")
nb.train("", "get kelvin status")
nb.train("", "get level status")
nb.train("", "set level status")
nb.train("", "get contact status")
nb.train("", "get smoke status")
nb.train("", "get garage status")
nb.train("", "open garage")
nb.train("", "close garage")
nb.train("", "get shade status")
nb.train("", "open shade")
nb.train("", "preset shade")
nb.train("", "close shade")
nb.train("", "get water sensor status")
nb.train("", "get battery status")
nb.train("", "get door lock status")
nb.train("", "lock door lock")
nb.train("", "unlock door lock")
nb.train("", "get presence status")
nb.train("", "get motion status")
nb.train("", "get outlet status")
nb.train("", "get meter status")
nb.train("", "turn on outlet")
nb.train("", "turn off outlet")
nb.train("", "get switch status")
nb.train("", "turn on switch")
nb.train("", "turn off switch")
nb.train("", "get temp sensors status")
nb.train("", "outlet handler")
nb.train("", "update door lock")
nb.train("", "update outlet")
nb.train("", "update switch")
nb.train("", "hello actions")
nb.train("", "execute action")
nb.train("", "structure info")
nb.train("", "acquiredata")
nb.train("", "create subscriptions")
nb.train("", "switch off handler")
nb.train("", "switch on handler")
nb.train("", "lights out")
nb.train("", "door opened")
nb.train("", "page with ip")
nb.train("", "registration handler")
nb.train("", "bridge discovery")
nb.train("", "bridge discovery failed")
nb.train("", "bridge linking")
nb.train("", "bulb discovery")
nb.train("", "get hue bridges")
nb.train("", "get verified hue bridges")
nb.train("", "manual refresh")
nb.train("", "add bulbs")
nb.train("", "add bridge")
nb.train("", "ssdp bridge handler")
nb.train("", "do device sync")
nb.train("", "is valid source")
nb.train("", "is in bulb discovery")
nb.train("", "parse")
nb.train("", "update handler")
nb.train("", "hub verification")
nb.train("", "on")
nb.train("", "off")
nb.train("", "set level")
nb.train("", "set saturation")
nb.train("", "set hue")
nb.train("", "set color temperature")
nb.train("", "convert bulb list to map")
nb.train("", "hex to hsv")
nb.train("", "hsv to hex")
nb.train("", "humidity handler")
nb.train("", "list")
nb.train("", "list states")
nb.train("", "list subscriptions")
nb.train("", "update")
nb.train("", "show")
nb.train("", "add subscription")
nb.train("", "remove subscription")
nb.train("", "device handler")
nb.train("", "get access key")
nb.train("", "get bucket key")
nb.train("", "set bucket key")
nb.train("", "set access key")
nb.train("", "try create bucket")
nb.train("", "generic handler")
nb.train("", "try ship events")
nb.train("", "acceleration active handler")
nb.train("", "temperature handler")
nb.train("", "sendit")
nb.train("", "build redirect url")
nb.train("", "receive token")
nb.train("", "received token")
nb.train("", "validate current token")
nb.train("", "setup")
nb.train("", "response goals")
nb.train("", "response moves")
nb.train("", "set color ")
nb.train("", "hook event handler")
nb.train("", "check server")
nb.train("", "cooling setpoint handler")
nb.train("", "heating setpoint handler ")
nb.train("", "heating setpoint handler")
nb.train("", "event")
nb.train("", "acceleration inactive handler")
nb.train("", "check running")
nb.train("", "subscribe")
nb.train("", "door open")
nb.train("", "door open too long")
nb.train("", "contact handler")
nb.train("", "get credentials page")
nb.train("", "get credentials error page")
nb.train("", "test life connection")
nb.train("", "initialize life connection")
nb.train("", "list circles ")
nb.train("", "list places")
nb.train("", "list users ")
nb.train("", "create circle subscription")
nb.train("", "generate initial event ")
nb.train("", "haversine")
nb.train("", "place event handler")
nb.train("", "apiurl")
nb.train("", "get secret key")
nb.train("", "get client id")
nb.train("", "oauth init")
nb.train("", "oauth callback")
nb.train("", "oauth receive token")
nb.train("", "oauth success")
nb.train("", "oauth failure")
nb.train("", "oauth received token")
nb.train("", "oauth connection status")
nb.train("", "log response")
nb.train("", "log errors")
nb.train("", "apiget")
nb.train("", "apiput")
nb.train("", "devices list")
nb.train("", "devices in location")
nb.train("", "update devices")
nb.train("", "page setup")
nb.train("", "page setup scenario a")
nb.train("", "page setup scenario b")
nb.train("", "page setup scenario c")
nb.train("", "page setup scenario d")
nb.train("", "on event a")
nb.train("", "delay turn off a")
nb.train("", "on press a")
nb.train("", "on event b")
nb.train("", "delay turn off b")
nb.train("", "on press b")
nb.train("", "on event c")
nb.train("", "delay turn off c")
nb.train("", "on press c")
nb.train("", "on event d")
nb.train("", "delay turn off d")
nb.train("", "on press d")
nb.train("", "mid night reset")
nb.train("", "grey out")
nb.train("", "greyed out time")
nb.train("", "get title")
nb.train("", "get desc")
nb.train("", "get midnight")
nb.train("", "get time label")
nb.train("", "contact closed handler")
nb.train("", "presence handler")
nb.train("", "is active presence")
nb.train("", "set time callback")
nb.train("", "door open check")
nb.train("", "lock message")
nb.train("", "get servercallback url")
nb.train("", "get harmonydevices")
nb.train("", "discovery")
nb.train("", "activity")
nb.train("", "activity response")
nb.train("", "poll")
nb.train("", "poll response")
nb.train("", "get activity list")
nb.train("", "get activity name")
nb.train("", "get activity id")
nb.train("", "get hub name")
nb.train("", "send notification")
nb.train("", "list devices")
nb.train("", "get device")
nb.train("", "update device")
nb.train("", "list phrases")
nb.train("", "execute phrase")
nb.train("", "send to harmony")
nb.train("", "list hubs")
nb.train("", "get hub")
nb.train("", "activity callback")
nb.train("", "get harmony")
nb.train("", "harmony")
nb.train("", "delete harmony")
nb.train("", "check open draw in past")
nb.train("", "check open draw after reminder")
nb.train("", "is opened")
nb.train("", "set led notification")
nb.train("", "reset led notification")
nb.train("", "check motion in past")
nb.train("", "check motion after reminder")
nb.train("", "is moved")
nb.train("", "get time window msec")
nb.train("", "button handler")
nb.train("", "scenes page")
nb.train("", "scene page")
nb.train("", "device page")
nb.train("", "save states page")
nb.train("", "position handler")
nb.train("", "toggle switches")
nb.train("", "refresh token")
nb.train("", "get device list")
nb.train("", "create child device")
nb.train("", "api get")
nb.train("", "c to pref")
nb.train("", "rain to pref")
nb.train("", "page two")
nb.train("", "touch handler")
nb.train("", "set sunrise")
nb.train("", "set sunset")
nb.train("", "change sun mode")
nb.train("", "set away")
nb.train("", "set timer")
nb.train("", "reset hue")
nb.train("", "start timer callback")
nb.train("", "stop timer callback")
nb.train("", "get inputs")
nb.train("", "register all device subscriptions")
nb.train("", "register device change")
nb.train("", "unregister device change")
nb.train("", "register device graph")
nb.train("", "unregister device graph")
nb.train("", "device event handler")
nb.train("", "location event handler")
nb.train("", "dock sensor")
nb.train("", "check and update plant if needed")
nb.train("", "moisture handler")
nb.train("", "battery handler")
nb.train("", "get device serial from event")
nb.train("", "swap token")
nb.train("", "parse api response")
nb.train("", "subscriber identify verification")
nb.train("", "update wink subscriptions")
nb.train("", "create wink subscription")
nb.train("", "delete wink subscription")
nb.train("", "remove wink subscriptions")
nb.train("", "build callback url")
nb.train("", "api put")
nb.train("", "c to f")
nb.train("", "f to c")
nb.train("", "dollarize")
nb.train("", "create nimbus children")
nb.train("", "cloud clock event handler")
nb.train("", "poll nimbus")
nb.train("", "get eggtray update")
nb.train("", "run egg report")
nb.train("", "eggtray event handler")
nb.train("", "get piggy bank update")
nb.train("", "piggy bank event handler")
nb.train("", "get sensor pod update")
nb.train("", "sensor pod event handler")
nb.train("", "powerstrip event handler")
nb.train("", "poll outlet")
nb.train("", "create powerstrip children")
nb.train("", "car presence")
nb.train("", "garage door contact")
nb.train("", "interior door closed")
nb.train("", "acceleration active")
nb.train("", "select routines")
nb.train("", "check sun")
nb.train("", "set home")
nb.train("", "send away")
nb.train("", "send home")
nb.train("", "trigger contact")
nb.train("", "trigger motion")
nb.train("", "trigger knock")
nb.train("", "trigger temp")
nb.train("", "trigger axis")
nb.train("", "send http")
nb.train("", "schedule job")
nb.train("", "check for severe weather")
nb.train("", "description filter")
nb.train("", "location is defined")
nb.train("", "zipcode is valid")
nb.train("", "hebcal  web request")
nb.train("", "today = new  date")
nb.train("", "locale = get weather feature")
nb.train("", "timezone =  time zone.get time zone")
nb.train("", "heb cal  get time")
nb.train("", "return time  = hebcal title.split")
nb.train("", "return time  = hebcal date.split")
nb.train("", "set chag")
nb.train("", "end chag")
nb.train("", "handle devices with ids")
nb.train("", "remove all subscriptions")
nb.train("", "send to roomie")
nb.train("", "agent discovery")
nb.train("", "manual agent entry")
nb.train("", "verify manual entry")
nb.train("", "discover agents")
nb.train("", "agents discovered")
nb.train("", "get agents")
nb.train("", "add or update agent")
nb.train("", "geturn")
nb.train("", "get uuid from usn")
nb.train("", "string  convert hex to ip")
nb.train("", "integer  convert hex to int")
nb.train("", "string  convert to hex string")
nb.train("", "string  convert ip to hex string")
nb.train("", "boolean  can install labs")
nb.train("", "boolean  has all hubs over")
nb.train("", "list  get real hub firmware versions")
nb.train("", "agent selection")
nb.train("", "control")
nb.train("", "select phrases")
nb.train("", "jawbone handler")
nb.train("", "page about")
nb.train("", "page uninstall")
nb.train("", "page status")
nb.train("", "page history")
nb.train("", "page select zones")
nb.train("", "page configure zones")
nb.train("", "page arming options")
nb.train("", "page alarm options")
nb.train("", "page notifications")
nb.train("", "page remote options")
nb.train("", "page rest api options")
nb.train("", "on contact")
nb.train("", "on motion")
nb.train("", "on movement")
nb.train("", "on smoke")
nb.train("", "on water")
nb.train("", "on button event")
nb.train("", "arm away")
nb.train("", "arm stay")
nb.train("", "disarm")
nb.train("", "panic")
nb.train("", "reset")
nb.train("", "exit delay expired")
nb.train("", "api arm away")
nb.train("", "api arm stay")
nb.train("", "api disarm")
nb.train("", "api panic")
nb.train("", "api status")
nb.train("", "activate alarm")
nb.train("", "white list")
nb.train("", "check access token")
nb.train("", "request code")
nb.train("", "set summary")
nb.train("", "get initial data")
nb.train("", "console log")
nb.train("", "get html")
nb.train("", "get encored push")
nb.train("", "start process ")
nb.train("", "start day")
nb.train("", "inc day")
nb.train("", "mid night")
nb.train("", "sched desc")
nb.train("", "create day array")
nb.train("", "switch change")
nb.train("", "set active and schedule")
nb.train("", "turn off motion after delay")
nb.train("", "motion")
nb.train("", "intruder motion")
nb.train("", "resident motion")
nb.train("", "contact")
nb.train("", "alarm")
nb.train("", "check for re arm")
nb.train("", "sound siren")
nb.train("", "continue flashing")
nb.train("", "weather check")
nb.train("", "chat message to mc")
nb.train("", "linker page")
nb.train("", "update switch level")
nb.train("", "update block level")
nb.train("", "update switch state")
nb.train("", "update block state")
nb.train("", "get block id")
nb.train("", "get linker description")
nb.train("", "list page")
nb.train("", "server page")
nb.train("", "notifier page")
nb.train("", "chat page")
nb.train("", "create block")
nb.train("", "ack")
nb.train("", "update block")
nb.train("", "send data to block")
nb.train("", "delete block")
nb.train("", "destroyed page")
nb.train("", "redstone page")
nb.train("", "neighbor block page")
nb.train("", "message builder page")
nb.train("", "smart phone notification section")
nb.train("", "chat section")
nb.train("", "message builder section")
nb.train("", "message builder href")
nb.train("", "chat closest player section")
nb.train("", "page state complete")
nb.train("", "smart block destroyed handler")
nb.train("", "smart block neighbor changed handler")
nb.train("", "redstone signal strength handler")
nb.train("", "notify user of redstone change")
nb.train("", "notify user of neighbor change")
nb.train("", "notify user")
nb.train("", "message description parts for page")
nb.train("", "message parts set")
nb.train("", "default message description")
nb.train("", "message description for page")
nb.train("", "message part default value")
nb.train("", "message")
nb.train("", "message builder options")
nb.train("", "get message part from option")
nb.train("", "get latest close player")
nb.train("", "settings as ids")
nb.train("", "convert block setting to block id")
nb.train("", "all blocks parsed")
nb.train("", "all blocks")
nb.train("", "scheduled event")
nb.train("", "choose track")
nb.train("", "extract button number")
nb.train("", "handle button")
nb.train("", "toggle play pause")
nb.train("", "adjust volume")
nb.train("", "open valve")
nb.train("", "close valve")
nb.train("", "valve on handler")
nb.train("", "set start time")
nb.train("", "start page")
nb.train("", "global page")
nb.train("", "weather page")
nb.train("", "zipcode page")
nb.train("", "delay page")
nb.train("", "zone page")
nb.train("", "zone settings page")
nb.train("", "zone set page")
nb.train("", "plant set page")
nb.train("", "sprinkler set page")
nb.train("", "option set page")
nb.train("", "set page")
nb.train("", "install schedule")
nb.train("", "write settings")
nb.train("", "manual start")
nb.train("", "busy off")
nb.train("", "pre check")
nb.train("", "cycle on")
nb.train("", "cycle off")
nb.train("", "check run map")
nb.train("", "cycle loop")
nb.train("", "write cycles")
nb.train("", "resume")
nb.train("", "sync on")
nb.train("", "water stop")
nb.train("", "sub off")
nb.train("", "off pause check")
nb.train("", "water start")
nb.train("", "moisture")
nb.train("", "note")
nb.train("", "send it")
nb.train("", "set season")
nb.train("", "get rain today")
nb.train("", "get dpw days")
nb.train("", "create dpw map")
nb.train("", "setup notifications")
nb.train("", "goal handler")
nb.train("", "step handler")
nb.train("", "lights notification")
nb.train("", "hue notification")
nb.train("", "sonos notification")
nb.train("", "sunrise handler")
nb.train("", "sunset handler")
nb.train("", "get pref")
nb.train("", "page main")
nb.train("", "page weather settings a")
nb.train("", "page weather settings b")
nb.train("", "page weather settings c")
nb.train("", "page weather settings d")
nb.train("", "alarm a")
nb.train("", "alarm b")
nb.train("", "alarm c")
nb.train("", "alarm d")
nb.train("", "get summary ")
nb.train("", "get weather desc")
nb.train("", "grey out option")
nb.train("", "dimmer desc")
nb.train("", "thermostat desc")
nb.train("", "uninstall from child device")
nb.train("", "setup bulbs")
nb.train("", "get gateway data")
nb.train("", "get token")
nb.train("", "api post")
nb.train("", "calculate current power use")
nb.train("", "generate sha")
nb.train("", "generatemd")
nb.train("", "check devices online")
nb.train("", "syncronize devices")
nb.train("", "debug out")
nb.train("", "poll room")
nb.train("", "login to tesla")
nb.train("", "select cars")
nb.train("", "getcar list")
nb.train("", "remove child from settings")
nb.train("", "log handler")
nb.train("", "on handler")
nb.train("", "off handler")
nb.train("", "dim handler")
nb.train("", "sensor change")
nb.train("", "restore")
nb.train("", "director settings")
nb.train("", "thermostatand doors")
nb.train("", "thermostat boost")
nb.train("", "settings")
nb.train("", "mode boost change")
nb.train("", "thermo shut off trigger")
nb.train("", "thermo shut off")
nb.train("", "door check")
nb.train("", "greyed out")
nb.train("", "greyed out therm")
nb.train("", "greyed out settings")
nb.train("", "thermo change")
nb.train("", "window change")
nb.train("", "list all")
nb.train("", "list contact sensors")
nb.train("", "show contact sensor")
nb.train("", "add contact subscription")
nb.train("", "remove contact sensor subscription")
nb.train("", "list presence sensors")
nb.train("", "show presence sensor")
nb.train("", "add presence subscription")
nb.train("", "remove presence sensor subscription")
nb.train("", "add switch subscription")
nb.train("", "remove switch subscription")
nb.train("", "list motions")
nb.train("", "show motion")
nb.train("", "add motion subscription")
nb.train("", "remove motion subscription")
nb.train("", "add lock subscription")
nb.train("", "remove lock subscription")
nb.train("", "motion open handler")
nb.train("", "current state")
nb.train("", "show states")
nb.train("", "list phrases with type")
nb.train("", "setup")
nb.train("", "time interval input")
nb.train("", "list all devices")
nb.train("", "get data from wattvision")
nb.train("", "get data for child")
nb.train("", "wattvisionurl")
nb.train("", "get data")
nb.train("", "child marshaller")
nb.train("", "create device")
nb.train("", "delete device")
nb.train("", "set api access")
nb.train("", "schedule data collection")
nb.train("", "revoke api access")
nb.train("", "login callback")
nb.train("", "create child")
nb.train("", "connection successful")
nb.train("", "update current weather")
nb.train("", "calculate dew point")
nb.train("", "get app info")
nb.train("", "get loc")
nb.train("", "get current report")
nb.train("", "set temperature")
nb.train("", "push latest")
nb.train("", "get or default")
nb.train("", "send to weather bug")
nb.train("", "devices discovered")
nb.train("", "switches discovered")
nb.train("", "motions discovered")
nb.train("", "light switches discovered")
nb.train("", "get wemo switches")
nb.train("", "get wemo motions")
nb.train("", "get wemo light switches")
nb.train("", "resubscribe")
nb.train("", "refresh")
nb.train("", "refresh devices")
nb.train("", "subscribe to devices")
nb.train("", "add switches")
nb.train("", "add motions")
nb.train("", "add light switches")
nb.train("", "ssdp switch handler")
nb.train("", "ssdp motion handler")
nb.train("", "ssdp light switch handler")
nb.train("", "check things")
nb.train("", "test")
nb.train("", "authenticate")
nb.train("", "exchange token from withings")
nb.train("", "notification received")
nb.train("", "st base url")
nb.train("", "st token")
nb.train("", "short url")
nb.train("", "no token url")
nb.train("", "attach params")
nb.train("", "unix time")
nb.train("", "backfill measures")
nb.train("", "w get measures")
nb.train("", "send measure events")
nb.train("", "parse measure group")
nb.train("", "parse measure")
nb.train("", "measure value")
nb.train("", "w notification base url")
nb.train("", "w notification callback url")
nb.train("", "w get notification")
nb.train("", "w create notification")
nb.train("", "w revoke all notifications")
nb.train("", "w revoke notification")
nb.train("", "w list notifications")
nb.train("", "default oauth params")
nb.train("", "fetch data from withings")
nb.train("", "w log enabled")
nb.train("", "request token url")
nb.train("", "user authorization url")
nb.train("", "exchange token url")
nb.train("", "exchange token")
nb.train("", "default parameter keys")
nb.train("", "oauth consumer key")
nb.train("", "oauth nonce")
nb.train("", "nonce")
nb.train("", "oauth signature method")
nb.train("", "oauth timestamp")
nb.train("", "oauth version")
nb.train("", "oauth callback")
nb.train("", "oauth token")
nb.train("", "oauth token secret")
nb.train("", "userid")
nb.train("", "collect token from withings")
nb.train("", "get consumer key")
nb.train("", "get consumer secret")
nb.train("", "get user id")
nb.train("", "render action")
nb.train("", "authorized html head")
nb.train("", "authorized html body")
nb.train("", "not authorized html head")
nb.train("", "not authorized html body")
nb.train("", "build oauth url with token")
nb.train("", "load")
nb.train("", "get measurement")
nb.train("", "parse json")
nb.train("", "measurement error")
nb.train("", "save measurement")
nb.train("", "event value")
nb.train("", "withings event")
nb.train("", "get withings device")
nb.train("", "should poll")
nb.train("", "get child namespace")
nb.train("", "get scale child name")
nb.train("", "get body analyzer child name")
nb.train("", "get smart things consumer key")
nb.train("", "get smart things consumer secret")
nb.train("", "config actions")
nb.train("", "check presence")
nb.train("", "build url")
nb.train("", "get server name")
nb.train("", "list available cameras")
nb.train("", "take picture")
nb.train("", "foauth")
nb.train("", "authorize")
nb.train("", "zwave event")
nb.train("", "configuration cmds")
nb.train("", "configure")
nb.train("", "status changed")
nb.train("", "contact triggered")
nb.train("", "motion triggered")
nb.train("", "sensor triggered")
nb.train("", "select alarm")
nb.train("", "select sensors")
nb.train("", "select states")
nb.train("", "ha settings page")
nb.train("", "other settings")
nb.train("", "set presence")
nb.train("", "arrived")
nb.train("", "left")
nb.train("", "handler")
nb.train("", "flush buffer")
nb.train("", "generateurl")
nb.train("", "viewurl")
nb.train("", "schedule turn on")
nb.train("", "mode handler")
nb.train("", "get ct bright")
nb.train("", "getct")
nb.train("", "get hex")
nb.train("", "gethsv")
nb.train("", "get bright")
nb.train("", "ct to rgb")
nb.train("", "rgb to hsv")
nb.train("", "config app")
nb.train("", "switch off")
nb.train("", "alarm switch contact")
nb.train("", "motion evt handler")
nb.train("", "take actions")
nb.train("", "select program")
nb.train("", "ask alexa mq handler")
nb.train("", "reschedule if needed")
nb.train("", "display tips page")
nb.train("", "get custom image path")
nb.train("", "select modes")
nb.train("", "climate list handler")
nb.train("", "set climate now")
nb.train("", "set climate")
nb.train("", "is right day for change")
nb.train("", "change fan min on time")
nb.train("", "set heating setpoint")
nb.train("", "clear heating setpoint")
nb.train("", "actions settings")
nb.train("", "thermostat mode handler")
nb.train("", "door unlocked handler")
nb.train("", "smoke handler")
nb.train("", "carbon monoxide handler")
nb.train("", "clear alert")
nb.train("", "switch hit")
nb.train("", "handle temperature event")
nb.train("", "handle humidity event")
nb.train("", "handle heating setpoint event")
nb.train("", "handle cooling setpoint event")
nb.train("", "handle thermostat mode event")
nb.train("", "handle fan mode event")
nb.train("", "handle humidifier mode event")
nb.train("", "handle humidifier level event")
nb.train("", "handle dehumidifier mode event")
nb.train("", "handle dehumidifier level event")
nb.train("", "handle ventilator mode event")
nb.train("", "handle fan min on time event")
nb.train("", "handle ventilator min on time event")
nb.train("", "handle thermostat operating state event")
nb.train("", "handle daily stats")
nb.train("", "handle equipment status event")
nb.train("", "handle program name event")
nb.train("", "handle water event")
nb.train("", "handle smoke event")
nb.train("", "handle carbon monoxide event")
nb.train("", "handle illuminance event")
nb.train("", "handle lock event")
nb.train("", "handle battery event")
nb.train("", "handle contact event")
nb.train("", "handle acceleration event")
nb.train("", "handle motion event")
nb.train("", "handle presence event")
nb.train("", "handle switch event")
nb.train("", "handle set level event")
nb.train("", "handle power event")
nb.train("", "handle energy event")
nb.train("", "handle cost event")
nb.train("", "process queue")
nb.train("", "on light off")
nb.train("", "on app touch")
nb.train("", "change color")
nb.train("", "start")
nb.train("", "stop")
nb.train("", "group discovery")
nb.train("", "create group")
nb.train("", "modify group")
nb.train("", "remove group")
nb.train("", "scene discovery")
nb.train("", "create scene")
nb.train("", "modify scene")
nb.train("", "change scene name")
nb.train("", "remove scene")
nb.train("", "init complete")
nb.train("", "default transition")
nb.train("", "get hue bulbs")
nb.train("", "get hue groups")
nb.train("", "get hue scenes")
nb.train("", "bulb list handler")
nb.train("", "group list handler")
nb.train("", "scene list handler")
nb.train("", "add groups")
nb.train("", "add scenes")
nb.train("", "set transition time ")
nb.train("", "set group scene")
nb.train("", "set to group")
nb.train("", "next level")
nb.train("", "get id")
nb.train("", "update scene from device")
nb.train("", "update scene")
nb.train("", "rename scene")
nb.train("", "delete scene")
nb.train("", "create new scene")
nb.train("", "update group")
nb.train("", "rename group")
nb.train("", "delete group")
nb.train("", "create new group")
nb.train("", "get bridge dni")
nb.train("", "get bridge hostname")
nb.train("", "get bridge hostname and port")
nb.train("", "convert group list to map")
nb.train("", "convert scene list to map")
nb.train("", "ip address from dni")
nb.train("", "get selected transition")
nb.train("", "set alert")
nb.train("", "set effect")
nb.train("", "is open")
nb.train("", "handle app touch")
nb.train("", "handle mode event")
nb.train("", "soft poll")
nb.train("", "log system properties")
nb.train("", "post to influx db")
nb.train("", "handle influx response")
nb.train("", "disable integration")
nb.train("", "enable integration")
nb.train("", "copy config")
nb.train("", "render config")
nb.train("", "device command map")
nb.train("", "authorized devices")
nb.train("", "render devices")
nb.train("", "device command")
nb.train("", "auth error")
nb.train("", "basic info")
nb.train("", "configure bulbs")
nb.train("", "all off")
nb.train("", "select things")
nb.train("", "tick")
nb.train("", "webhook")
nb.train("", "remove bulbs")
nb.train("", "update grp")
nb.train("", "get app version")
nb.train("", "dashboard page")
nb.train("", "sensor settings")
nb.train("", "humidify settings")
nb.train("", "dehumidify settings")
nb.train("", "ventilator settings")
nb.train("", "set humidity level")
nb.train("", "get image path")
nb.train("", "get app name")
nb.train("", "temp sensor settings")
nb.train("", "motion sensor settings")
nb.train("", "threshold settings")
nb.train("", "change mode handler")
nb.train("", "set climate evt handler")
nb.train("", "program heat evt handler")
nb.train("", "program cool evt handler")
nb.train("", "monitor adjust temp")
nb.train("", "lock handler")
nb.train("", "notify unlocked")
nb.train("", "identify")
nb.train("", "get clusters")
nb.train("", "enroll response")
nb.train("", "check door")
nb.train("", "button push")
nb.train("", "parse description as map")
nb.train("", "update state")
nb.train("", "set model")
nb.train("", "tile set level")
nb.train("", "set local level")
nb.train("", "get group status")
nb.train("", "play")
nb.train("", "pause")
nb.train("", "next track")
nb.train("", "previous track")
nb.train("", "seek")
nb.train("", "mute")
nb.train("", "unmute")
nb.train("", "set play mode")
nb.train("", "play text and resume")
nb.train("", "play track and resume")
nb.train("", "play text and restore")
nb.train("", "play track and restore")
nb.train("", "play text and track")
nb.train("", "play sound and track")
nb.train("", "play track at volume")
nb.train("", "play track")
nb.train("", "set track")
nb.train("", "resume track")
nb.train("", "restore track")
nb.train("", "play text")
nb.train("", "set text")
nb.train("", "unsubscribe")
nb.train("", "get volume")
nb.train("", "get current media")
nb.train("", "get current status")
nb.train("", "get system string")
nb.train("", "white")
nb.train("", "set color hex")
nb.train("", "cycle colors")
nb.train("", "get current level")
nb.train("", "striim light discovery")
nb.train("", "getstriim light player")
nb.train("", "get verifiedstriim light player")
nb.train("", "scheduled refresh handler")
nb.train("", "scheduled actions handler")
nb.train("", "addstriim light")
nb.train("", "select switches")
nb.train("", "push")
nb.train("", "hold")
nb.train("", "release")
nb.train("", "associate hub")
nb.train("", "get data by name")
nb.train("", "integer")
nb.train("", "integerhex")